#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pyxdameraulevenshtein
Version  : 1.7.0
Release  : 5
URL      : https://files.pythonhosted.org/packages/aa/e8/53d212009d6d40fdd98ef41585e5442812323d145aa47f507996093567f2/pyxDamerauLevenshtein-1.7.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/aa/e8/53d212009d6d40fdd98ef41585e5442812323d145aa47f507996093567f2/pyxDamerauLevenshtein-1.7.0.tar.gz
Summary  : pyxDamerauLevenshtein implements the Damerau-Levenshtein (DL) edit distance algorithm for Python in Cython for high performance.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-pyxdameraulevenshtein-python = %{version}-%{release}
Requires: pypi-pyxdameraulevenshtein-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
Provides: pyxDamerauLevenshtein
Provides: pyxDamerauLevenshtein-python
Provides: pyxDamerauLevenshtein-python3
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)

%description
# pyxDamerauLevenshtein
[![Build Status](https://travis-ci.com/gfairchild/pyxDamerauLevenshtein.svg?branch=master)](https://travis-ci.com/gfairchild/pyxDamerauLevenshtein)

%package python
Summary: python components for the pypi-pyxdameraulevenshtein package.
Group: Default
Requires: pypi-pyxdameraulevenshtein-python3 = %{version}-%{release}

%description python
python components for the pypi-pyxdameraulevenshtein package.


%package python3
Summary: python3 components for the pypi-pyxdameraulevenshtein package.
Group: Default
Requires: python3-core
Provides: pypi(pyxdameraulevenshtein)

%description python3
python3 components for the pypi-pyxdameraulevenshtein package.


%prep
%setup -q -n pyxDamerauLevenshtein-1.7.0
cd %{_builddir}/pyxDamerauLevenshtein-1.7.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641486982
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
